### ISSUE TITLE
transaction data refactoring

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#203]
# The scope of this issue changed

will follow this refactoring proposal: https://github.com/aeternity/elixir-research/issues/203#issuecomment-367045472

.

.

.

.

.

# Deprecated description

## plain data transaction

- custom signed_tx
- validate only signature, fees and nonce

```
%SignedTx{
  data: %DataTx{
              type: String.t(),
              payload: any type,
              from_acc: binary(),
              fee: integer(),
              nonce: non_neg_integer(),
            },
  signature: binary()
}
```

## proof of existence prototype

- type: ProofOfExistenceTx
- payload: hash of any file/data, base-encoded

------

 - in the future this can be used for other aepps transactions that need to be persisted in the blockchain
 - the plan is to merge this if ready, so #197 can depend on it

**Comment by gspasov** [comment]
Reviewing this code with @rdimitrovbg, we decided that this code could be done a bit better. Here is our idea:

Why don't we have a create a generic functionality in each of the different Transaction types (Tx modules) and that will construct the transaction in it's own module with it's own specifications (in there are any).

# Example 
```elixir
defmodule  Aecore.Structures.DataTx do
.
.
.
    defstruct [:type, :payload, :from_acc , :fee, :nonce]

    # Generic Tx creation function
    def create(type, payload, from_acc, fee, nonce) do
        tx_data =
           %DataTx{type: type, # This is the module name itself of the Transaction type (i.e. SpendTx | ContractProposalTx)  
                   payload: type.create(payload), # Here we call the generic creation function of each Transaction type
                   from_acc: from_acc,
                   fee: fee,
                   nonce: nonce}
        Keys.sign_tx(spend_tx)
    end
end
```

## Custom transaction 1
```elixir
defmodule Aecore.Structures.SpendTx do
.
.
.
    defstruct [:to_acc, :value, :lock_time_block] # Payload

    def create(%{to_acc: to_acc, value: value, lock_time_block: lock} = payload) do
        %SpendTx{to_acc: to_acc,
               value: value,
               lock_time_block: lock}
    end
end
```

## Custom transaction 2
```elixir
defmodule Aecore.Structures.ContractProposalTx do
.
.
.
    defstruct [:contract_hash, :contract_signature, :contract_name, :ttl] # Payload

    def create(%{contract_hash: hash, contract_signature: sign,
                         contract_name: name, ttl: ttl} = payload) do

        %ContractProposalTx{contract_hash: hash,
                       contract_signature: sign,
                       contract_name: name,
                       ttl: ttl}
    end
end
```

------

### So for the validation of the transaction for example this is how the workflow will be changed:

Here we can make each Transaction module have it's own is_valid?() func and call it from there like: 

```elixir
defmodule Aecore.Structures.SignedTx do
.
.
.
    def is_valid?(%SignedTx{data: data_tx} = tx) do
        Aecore.Structures.DataTx.is_valid?(data_tx)
    end
end 
```

```elixir
defmodule Aecore.Structures.DataTx do
.
.
.
    def is_valid?(%DataTx{type: type, payload: payload, fee: fee} = data_tx) do
        if (tx.data.fee >= 0 && Keys.verify_tx(tx)) do
            type.is_valid?(payload)
        else
            false
        end
    end
end 
```

```elixir
defmodule Aecore.Structures.SpendTx do
.
.
.
    def is_valid?(%SpendTx{value: value} = payload) do
        tx.data.value >= 0
    end
end 
```

**Comment by thepiwo** [comment]
@gspasov @rdimitrovbg can you set yourself a timeframe to finish this task? Maybe the end of the week?

**Comment by gspasov** [comment]
In our minds we could finish in **Friday - 02.03.2018**

**Comment by gspasov** [comment]
## Roadmap Update
Since we are having some trouble refactoring the serialization, fixing the tests and @rdimitrovbg and I
are, at the same time, working on other issues as well, we'll have to postpone the finish date to: **Tuesday - 03.13.2018**
