### ISSUE TITLE
extract coinbase transaction as own structure

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#228]
this should include 3 fields, account (which is the miner and receiver of the amount), height of the block and amount

**Comment by thepiwo** [comment]
@cheezus1 what is the progress here?

**Comment by thepiwo** [comment]
@cheezus1 what is the progress here?

**Comment by thepiwo** [comment]
this issue will get an updated specification to match aeternity specifications, once #203 is finished

**Comment by cytadela8** [comment]
I'm doing this as part of transactions refactoring for multisig transactions for #294

**Comment by thepiwo** [comment]
It is not yet decided, if this will be part of the header in aeternity specification.

**Comment by thepiwo** [comment]
@cytadela8 this is still not decided for the final aeternity specification, they will include the changes with NG-consensus. Maybe we should extract the coinbase as separate structure, to match the current epoch implementation.

**Comment by cytadela8** [comment]
Ok, so as you suggested we will have a separate structure for now? If they put it in header we will just remove this new tx type and add coinbase handling somewhere else.

**Comment by thepiwo** [comment]
yes okay

**Comment by thepiwo** [comment]
@cytadela8 will you create a PR for this, soon?
