### ISSUE TITLE
extract state structure handling

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#252]
To goal is to have each kind of state in a separate structure inside the chainstate. 

```
{
 accounts: account_state,
 oracle: oracle_state,
 voting: voting_state
}
```

This task should make the following refactoring:
 - make chain state structure with type, represent top structure in structures folder 
 - move applying functions from chain_state to the structure (I think that are all functions for now, but keep the chain_state as wrapper, call should be e.g. `chain worker` -> `chain_state` -> `state structure`, we will need this as later tickets refactor the state structure to tree representation but the api to current functionality should stay the same)

**Comment by rdimitrovbg** [comment]
Is the `chainstate` dynamic structure seen through the prism of the blockchain ?
"when we think about the keys in a key <-> value based structure"

Let assume that we run the main net with `chainstate` structure defined like so 
chainstate = 
	%{
		key1: val1
		key2: val2
	}
Where key(n) is the actual type
Currently we have two keys and some related value. 
Does the addition/deleting of a key(type) to the current `chainstate` provoke unwanted events in ideology blockchain ?

PS:
The еnhanced functionality we did together with @gspasov on #203 , does it cover the requirement or we should think of a new way of functionality and structure of chainstate?
What do you meen by: "make chain state structure with `type`, represent top structure in structures folder"

**Comment by thepiwo** [comment]
I don't quite understand your question, we will refactor the chain state to be represented by trees in multiple steps. The content and structure of this tree will get hashed using the merkle root hash and this will get included in the block header, so it is critical to blockchain consensus.

Yes, maybe #203 covers one requirement. But I want the account functionalities of the chainstate moved to a seperate module, if possible, as we will add more kinds of state in the future. e.g. oracle, voting, naming

**Comment by thepiwo** [comment]
@rdimitrovbg ?

**Comment by rdimitrovbg** [comment]
@thepiwo 
I wondered if, after the launch of the main network, a change in the 'chainstate' structure would have to affect the performance of the network?

Initially we have three fields. Accounts, Oracles and Voting. Subsequently, new fields will be added.
How will this change the network, if it changes at all?

**Comment by thepiwo** [comment]
1. the change itself would not, but the changes may.
2. initially we only have accounts. Once oracles, voting, channels and naming are supported, these will be added. This won't change the network, but the consensus rules. The chain state root hash have to match everybody elses. If a new kind of state is there has to be either hard or softfork to support it across the network, using an increased block version number.

**Comment by cytadela8** [comment]
Doesn't this create problems with #254? If we separate accounts, oracle and votings states into separate containers it will be problematic to have one chain_state hash. Wouldn't it be simpler to store different objects types on blockchain in one chain_state container (map/petricia merkle tree)? This way the chain_state hash will be just the root hash of the petricia merkle tree with all of the chain_state objects and a proof of any object state will be just a proof from the merkle tree.

**Comment by thepiwo** [comment]
yes it will be one chain_state container, where this the extracted structures will get part of a big tree of separate trees, as epoch does - to get compatible.

**Comment by rdimitrovbg** [comment]
Currently, chainstate is a map. Should we think of changing it to merkle tree?
And to think for a way to apply "RW - read/write" functionality ?

**Comment by thepiwo** [comment]
@rdimitrovbg yes this will be a follow-up task. Actually there are 2:
 1. extract what is now `AccountStateTree` to be generic for other StateTree implementations
 2. have the chainstate represented as tree of the separate state trees

Can you quickly give me your opinion on these tasks, but these are for sure scheduled to be done, after this is merged. 2. would include research on how this is implemented in epoch.

**Comment by rdimitrovbg** [comment]
1. Yes, it was conceived with this idea.
2. By converting AccountStateTree into a generic one, we will be able to easily control any current or new come key-value pair. (type-data) ( %Account{} => accounts_state)
We are still considering a variant, a mechanism that will untie our hands from limitation of ```case do ``` scenario.
Ok, we will familiarize with epoch approach.
@thepiwo

**Comment by cytadela8** [comment]
Storing trees in trees would be problematic as any change to subtree would require deserializing and serializing it back. If we really would like to do that this way I would suggest the root_hash to be just a hash of concatenated trees hashes. I don't think there is any real gain for proving the tree hash value with root_hash when there is less then 6 trees.

**Comment by cytadela8** [comment]
I would investigate whats the important reason core team decided to split the trees. If we really want to go with this I can later write some efficient code for storing merkle trees as leafs in a merkle tree.

**Comment by cytadela8** [comment]
Of course epoch team might have some clean solution already.

**Comment by thepiwo** [comment]
as mentioned previously

> 2. would include research on how this is implemented in epoch.

I am not to sure how they handle it, their overall chainstate object is called trees, but maybe map structure
