### ISSUE TITLE
adjust block / header field encoding

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#256]
- [ ] encode `prev_hash` using base58c
- [ ] encode `root_hash` using base58c
- [ ] encode `txs_hash` using base58c
- [ ] encode `txs` using base58c for each tx over the binary(msgpack) representation

**Comment by Artur64** [comment]
@thepiwo So, Base58check encoding function requires a prefix, where the length of this prefix should be 32 bytes , which prefix should we use to encode values?For instance, we can use a <<0,0,0,0>>.

**Comment by thepiwo** [comment]
Yes I will find out the prefixes and will add them here. They are 2 letters + $ sign.

**Comment by thepiwo** [comment]
block_hash: "bh"
block_tx_hash: "bx"
block_state_hash: "bs"
transaction: "tx"
oracle_pubkey: "ok"
account_pubkey: "ak"

**Comment by Artur64** [comment]
@thepiwo The problem is , if we encode "data" string with prefix which, for example, is "bh$" (3 symbols) the result will be something like  "RQLjjhBnufbRs84", which, if we decode it - we will get a tuple with 2 elements ( {prefix, data} ) - {"bh$d", "ata"}. I'm not quite sure that a part of the data should be in prefix, i think we should add 1 more symbol ( "$" , or even an empty string will do the job), so the data won't be divided.

**Comment by thepiwo** [comment]
you have to adjust the binary prefix so that the decoded version matches the prefix

**Comment by thepiwo** [comment]
This should be possible anyways, maybe a issue with the library, but you can work around this

**Comment by thepiwo** [comment]
@Artur64 You can use arbitrary prefixes as well
`"ac" <> "$" <> Base58Check.encode58(<<8,1,2,3>>)` works for me

**Comment by thepiwo** [comment]
@Artur64 does this work for you? What is the progress?

**Comment by Artur64** [comment]
@thepiwo I switched to another library written in Erlang ( https://github.com/helium/erl-base58 ) , by this moment it works perfect, I will continue working on failing client and http tests and will commit these changes as soon as im ready .

**Comment by thepiwo** [comment]
Did you look at the solution I provided?

**Comment by Artur64** [comment]
@thepiwo Yes , i'm using it
