### ISSUE TITLE
adjust timestamp validation

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#261]
adjust timestamp validation, for the block not to be more than a configurable value in the future (30min as default)

(keep the old timestamp validation code, as I assume this will get changed again in the future)

**Comment by HristianHristov** [comment]
@thepiwo Wasn't this done in #323 ? Why it's still open?

**Comment by thepiwo** [comment]
because the closes annotation has to be typed twice if it should close two issues, which has been done with comma.
