### ISSUE TITLE
remove locktime

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#262]
remove locktime for now 

(will maybe be added back in some form: https://www.pivotaltracker.com/story/show/152484155)

**Comment by rdimitrovbg** [comment]
"lock_time_block" at the moment this variable is located in "SpendTx," the role it occupies is to "lock" a transaction in order to avoid the forking. What other mechanism will we provide to deal with this problem ?

**Comment by thepiwo** [comment]
@rdimitrovbg I don't understand what you mean with avoiding forks? We remove it for now, but it will be added back later in one form or another, as described in the referenced ticket.

@DanielaIvanova yes

**Comment by rdimitrovbg** [comment]
@thepiwo I'm sorry, my mistake. What I meant was to prevent from double spending not  ... avoid forks.

**Comment by thepiwo** [comment]
Still, I don't get it. Can you describe what double spend problems you see?

**Comment by thepiwo** [comment]
@rdimitrovbg ?

**Comment by thepiwo** [comment]
@DanielaIvanova @rdimitrovbg what is the state of this? - if finished PR it

**Comment by rdimitrovbg** [comment]
@thepiwo 
Apologies.
I was looking for opinions and suggestions.
I understand the idea of lock_time_block in the following way.

The Lock_time_block locks the transactions in a block for a certain time.
The time needed for the network to "refresh".
Time as a guarantee that transactions are legit.

^^^( there is a need for a "chain" longer at least  n blocks "where 'n' is lock_time_block = value" )

We know the longest "chain" wins.
By reducing this difficulty (lock_time_block) opens the possibility for more frequent meetings of "chains" at a lower priority.

And I thought.
Do we get a lot forks and pandora of transaction scenarios ? (And may be the double spend)

Or my understand of lock_time_block is not right.

**Comment by thepiwo** [comment]
it can be used like this, but we only used it to lock coinbase rewards for some blocks, to minimize malicious usage of small forks.

As suggested in the task at the top, we will add it back sometime, but potentially with other specs.
https://www.pivotaltracker.com/story/show/152484155
