### ISSUE TITLE
include version number in specific transactions

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#281]
- [x] use hardcoded value, 1 for now
- [x] add version to spend_tx

**Comment by gspasov** [comment]
Should this version do something or be checked for some value, or just add it there for the time being

**Comment by gspasov** [comment]
Should I hardcode this value somewhere in the config ?

**Comment by thepiwo** [comment]
yes, add it to the config

**Comment by gspasov** [comment]
@thepiwo Should there be a func to update the version, or it'll always be a hardcoded value?

**Comment by thepiwo** [comment]
for now hardcoded is fine
