### ISSUE TITLE
refactor fee deduction update to be in data tx

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#303]

**Comment by gspasov** [comment]
The last transaction validation checks are done in SpendTx, eg: if balance is negative after deducting the `fee+amount_to_send`, and if nonce is correct. How should then we move the nonce update and fee deduction to DataTx module, before having checked the data? Should then the check move as well? But the balance info is stored in the SpendTx?

**Comment by thepiwo** [comment]
hmm, I don't have a clear idea how it should work for fees, @0legIv already did it for nonces un #304

**Comment by thepiwo** [comment]
@cytadela8 do you have an idea how to abstract this correctly, so we minimize duplicate code for custom transaction types?

**Comment by 0legIv** [comment]
As @gspasov suggested, I moved deduct_fee function to the DataTx. So when we have new types of txs, we can easily call this function from their parent - DataTx.

**Comment by thepiwo** [comment]
I think this is fine.
@gspasov if we substract fee in abstract and amount in specific transactions, it should be possible to check afterwards if balance is >= 0 for validation

**Comment by thepiwo** [comment]
@0legIv can you add a test where `amount < balance`, `fee < balance` but `amount + fee > balance` sothe transaction is filtered as invalid

**Comment by gspasov** [comment]
My suggestion was to only more the declaration of the function to DataTx module, but the its usage will stay inside the SpendTx module, so that we can check that fee+amount <= balance

**Comment by cytadela8** [comment]
My suggestion is to handle fee deduction in each transaction type separately. I don't really see a way around this. For example in channels there are transactions signed by two parties, but only one pays. We might want to change that in future. We might want to have a system like in Ethereum at some point (the transaction cost isn't know before execution). To make it a little bit nicer in my current changes for channel implementation I kept the fee code separated, but it's called from DataTx. This way it's not possible to forget about fee when implementing new transaction type.

**Comment by cytadela8** [comment]
Another option (not my suggestion) is to just move it to DataTx and only leave it's validation in modules implementing Transaction.
