### ISSUE TITLE
check nonce to always be bigger than previous

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#304]

**Comment by 0legIv** [comment]
Hello Philipp, I have a question about this issue: there is already created function to check if the nonce is less then account nonce, it is called preprocess_check https://github.com/aeternity/elixir-node/blob/4926aa8d55e8761d665ceee50c26735195bcec60/apps/aecore/lib/aecore/structures/spend_tx.ex . So what exactly needs to be done in this issue?

**Comment by thepiwo** [comment]
this code says `account_state.nonce >= nonce` where "always be bigger than previous" would nonce > account_state.nonce, if I am correct, maybe there is more to this code, I don't see ad-hoc.

The nonce should be checked for all `DataTx`, as this is the structure it is included in, not `SpendTx`.
