### ISSUE TITLE
add multi node sync testcase

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#307]
fail test if nodes don't sync
maybe has to be done in python

**Comment by d-velev** [comment]
We can maybe use System.cmd to start another node and kill the process when the test is done

**Comment by 0legIv** [comment]
This issue is blocked until pull request #379 is merged. I can continue working on it but without using sync, so it's better to merge this pull request as soon as possible.

**Comment by thepiwo** [comment]
there you go @0legIv, merged it

**Comment by 0legIv** [comment]
Will close it to avoid code duplication. The work will be continued in issue #417
