### ISSUE TITLE
replace msgpack with ethereum rlp for binary serialization

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#335]
## Documentations:

General Ethereum RLP:
 - https://github.com/ethereum/wiki/wiki/RLP

Epoch serialization:
 - https://github.com/aeternity/protocol/blob/master/serializations.md

Epoch Erlang implementation:
 - https://github.com/aeternity/epoch/blob/master/apps/aecore/src/aec_object_serialization.erl

**Comment by Artur64** [comment]
This issue is blocked until issue #357  is resolved.

**Comment by thepiwo** [comment]
can't we replace this for everything except oracles, so code could fail for oracles, but it wouldn't block?

**Comment by Artur64** [comment]
@thepiwo  Ok, i think, i might continue working on other structures, but if i will find some incompatibilities - i will try to serialize it wrong but atleast i will try to get it working

**Comment by vans163** [comment]
what is wrong with msgpack again?

**Comment by thepiwo** [comment]
@vans163 internally the core team discussed to favour the fomat of rlp more than msgpack, as some types have multiple valid encodings in msgpack, where rlp is canonical. So for the elixir implementation we have to adjust as well, to be compatible.

**Comment by vans163** [comment]
but rlp has like no types except list.  

And I think I see the discussion https://github.com/msgpack/msgpack/issues/215.

I would go for a bit level serializer if using something non-standard already. It could save a lot of bytes.

**Comment by thepiwo** [comment]
@vans163 we had this discussions in our team and I can't recall all of the details. If you want more specific answers about why we did choose rlp over other serialization, please ask in the [Forum](https://forum.aeternity.com/), for the decision-makers to come back to you.
