### ISSUE TITLE
new sync protocol using noise

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#336]
## Documentation:

https://github.com/aeternity/protocol/blob/sync/SYNC.md

**Comment by d-velev** [comment]
@gspasov @HristianHristov and @meivantodorov should be assigned as well

**Comment by thepiwo** [comment]
is this the only task 4 people are working on at the same time? Otherwise split this to smaller tasks and label this as tracking task.

**Comment by d-velev** [comment]
I'll exclude myself from this for now since I'm not doing anything for the sync module

**Comment by gspasov** [comment]
This will be closed with issue #359

**Comment by thepiwo** [comment]
So let's close this in favor of #359
