### ISSUE TITLE
represent oracles state as patricia merkle tree

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#349]

**Comment by rdimitrovbg** [comment]
This commit includes:
- merge with master at point of 4ccf924665b93f24241a34f27aa15faef85927b7
- merge with GH-335 at point of  1601fe4aa3a2720156289d47672916417b964cea
- ability to make a RegistrationTx [Reimplementing]
- including of external library sext (erlang)
- new credo version
