### ISSUE TITLE
Adjust Oracle structures to match Erlang implementation

### ISSUE THREAD

**Issue by Artur64** [aeternity/elixir-node#357]
To continue the work on issue #335 , our Oracle structures must match the Erlang implementations.

Here are some examples of incompatibilities:
1) TTLs of registered Oracles chain-state -  Our structure - a map with ttl_type and ttl itself , their implementation - have only field expires: https://github.com/aeternity/epoch/blob/master/apps/aeoracle/src/aeo_oracles.erl#L48 ,
which, i suppose, is being calculated here: https://github.com/aeternity/epoch/blob/master/apps/aeoracle/src/aeo_oracles.erl#L83
2) Query/Response formats: Our structure - a map , their implementation - UTF8 encoded string. 
(more info at https://github.com/aeternity/epoch/blob/master/apps/aeoracle/src/aeo_oracles.erl#L39 )
3) Query/response fields in our oracles interaction objects state should have fully composed DataTx with all data inside, not just %Aecore.Oracle.Tx.OracleQueryTx{}/some string 

And so on...

Useful links:
1) Erlang Oracle implementations: https://github.com/aeternity/epoch/tree/master/apps/aeoracle
2) OracleTxs: https://github.com/aeternity/epoch/blob/master/apps/aeoracle/include/oracle_txs.hrl
3) Their serializations file which is a bit outdated but still have some types described: https://github.com/aeternity/protocol/blob/master/serializations.md#oracles
4) Oracle utils https://github.com/aeternity/epoch/blob/master/apps/aeoracle/src/aeo_utils.erl

Of course there are more of incompatibilities, so we need to inspect whole Erlang code, find and make them compatible.

**Comment by thepiwo** [comment]
Did you notice other differences, if so could you specify them, because of "And so on..."

**Comment by Artur64** [comment]
Query field in our oracles interaction objects state should have fully composed DataTx with all data inside, not just %Aecore.Oracle.Tx.OracleQueryTx{}

**Comment by Artur64** [comment]
Same goes for response field

**Comment by thepiwo** [comment]
field renaming and structure can maybe be solved in serialization (as with transaction and blocks)

**Comment by thepiwo** [comment]
closed by https://github.com/aeternity/elixir-node/pull/367
