### ISSUE TITLE
Persist only root hash instead of whole state

### ISSUE THREAD

**Issue by rdimitrovbg** [aeternity/elixir-node#365]

**Comment by thepiwo** [comment]
@rdimitrovbg what is this supposed to do?
as it is `wontfix` can we close it?

**Comment by rdimitrovbg** [comment]
Sorry @thepiwo. I'm sure I did something wrong with my notification options.
I thought I had turned `wontfix` off it is **wrong**

After the changeing the states from map to patricia merkle tree (PMT) of the `accounts`, `oracles` and later the `naming`.
We no longer have to store their data in row format which will causes rapid growth of BD, instead what we store will be just the root_hash of one PMT. Using this root_hash we can create the same state back.

**Comment by thepiwo** [comment]
We need to persist the full trees, we plan to implement a full node, without pruning.

By only persisting the root_hash you can't recompute the tree from persisted data, so it would not be possible to extend or read trees from this.

**Comment by thepiwo** [comment]
closed by #405
