### ISSUE TITLE
Getting cuckoo compiled to use in NodeJS script

### ISSUE THREAD

**Issue by OluAgunloye** [aeternity/elixir-node#371]
Hey fellas,

We're trying to use cuckoo for in a NodeJS application and we're having problems finding a native implementation because JS can't do 64-bit int math.

We can see that elixir is using a fork of cuckoo compiled and imported to Node. Is there some documentation on how to build it and import from Node?

Any pointers would be very helpful, thank you.

P.S: This is the closest we've been able to find of a JS implementation in 64 bits: https://github.com/ZiRo-/cuckgo

John Tromp has also stated in a previous issue that he has yet to see a way to do this some months ago.

**Comment by thepiwo** [comment]
Hello, as this has nothing to do with the project I'm going to close this issue.

Regarding your question, we haven't tried or don't know about running cuckoo withing NodeJS or JS in general yet. For server usage it would maybe best to call the native cuckoo binaries, as we do here using erlang exec or nif. For client/browser usage you could try using WebAssembly, but I have no experience with this yet.
