### ISSUE TITLE
Reverse order of argument

### ISSUE THREAD

**Issue by rdimitrovbg** [aeternity/elixir-node#383]
### Description
According the `Transaction` behavior model, the order of arguments in function DataTx.deduct_fee/5 differ. Which causes abnormal work on other transactions.

**Comment by cytadela8** [comment]
Ok, I see now. Even when I looked at the code this time the order looked good to me, but in fact there is an error in DataTx.

**Comment by rdimitrovbg** [comment]
@thepiwo 
mistake
