### ISSUE TITLE
Mining when we have txs with the same nonce

### ISSUE THREAD

**Issue by gspasov** [aeternity/elixir-node#386]
There is a problem atm where if we create 2 txs with the following code:
``` elixir
receiver = <<2, 6, 116, 199, 199, 74, 217, 59, 14, 15, 61, 242, 155, 94, 172, 0, 175, 111, 117, 132, 252, 71, 77, 5, 254, 216, 126, 163, 58, 15, 126, 126, 230>>

{_, tx}= Aecore.Account.Account.spend(receiver, 50, 20)
```
This way the first tx will be correct, but the second will have the same nonce, resulting in an invalid tx, but if we add both of them to the Pool, and start mining we get the following error: 
``` bash
** (MatchError) no match of right hand side value: {:error, "Elixir.Aecore.Tx.DataTx: Nonce is too small: 3"}
    (aecore) lib/aecore/miner/worker.ex:298: Aecore.Miner.Worker.create_block/5
    (aecore) lib/aecore/miner/worker.ex:74: Aecore.Miner.Worker.mine_sync_block_to_chain/0
```

## Possible solution:
Filter the txs with invalid nonces in `ChainState.get_valid_txs()` or when adding a new tx to the pool

**Comment by thepiwo** [comment]
I don't see this as `low-priority`, all invalid transactions should be filtered while mining.

**Comment by cytadela8** [comment]
I can't seam to reproduce this bug. When creating to txs to one receiver they can't be added at the same time to pool. When creating two txs to the difference receivers I get correct behaviour. (One is mined, other is in Pool, too small nonce is reported through logger)

**Comment by gspasov** [comment]
Can't reproduce, problem seems to be already resolved in the current master branch!
