### ISSUE TITLE
Fix incorrect function specifications

### ISSUE THREAD

**Issue by DanielaIvanova** [aeternity/elixir-node#396]

**Comment by thepiwo** [comment]
where is this this issue? @0legIv why doesn't dialyzer catch thisß

**Comment by DanielaIvanova** [comment]
@thepiwo There are a lot of functions with wrong specifications. We will fix it in this issue

**Comment by thepiwo** [comment]
@0legIv could we find a way to not have these problems? otherwise dialyzer seems quite useless

**Comment by 0legIv** [comment]
@thepiwo The biggest problem is that it is very user unfriendly, so when you see the error it's not very clean how to solve it. But it can be useful in case if there is really wrong specification, dialyzer can show you this as warning. And these warnings are not harmful for the project, so my suggestion is - we can keep it in travis, but without halt-exit-status. In this case we will still see the warnings, but the Travis will be passed.

**Comment by thepiwo** [comment]
@DanielaIvanova @rdimitrovbg what is the state of this?

**Comment by DanielaIvanova** [comment]
@thepiwo 
We will open a PR regarding this issue, when PR#395 and PR#368 are done and merged in master, because this branch was made over issue#369.
