### ISSUE TITLE
Adjust Header and Block serializations 

### ISSUE THREAD

**Issue by Artur64** [aeternity/elixir-node#401]
Header serialization to binary should be adjusted according Epoch's implementation: [link](https://github.com/aeternity/epoch/blob/master/apps/aecore/src/aec_headers.erl#L109)

Block's RLP serializations, therefore, should be slightly adjusted too.

Epoch's serializations [file](https://github.com/aeternity/protocol/blob/master/serializations.md).
This issue depends on PR #400 .

**Comment by thepiwo** [comment]
@Artur64 I did merge PR #400
