### ISSUE TITLE
fix nakamoto consensus

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#451]
allow chain to be overwritten by longer ones

**Comment by cytadela8** [comment]
Doesn't this work? We keep track of top_block (longest chain) and forks should work as expected.

**Comment by cytadela8** [comment]
I found the discussion in #414. So I guess the problem is unknown and due to some changes since I last worked with that.

**Comment by gspasov** [comment]
I think this is fixed with #567

**Comment by thepiwo** [comment]
yes can be, let's assume it will be resolved and reopen another issue if the problem persists
