### ISSUE TITLE
account balance we never matching :none

### ISSUE THREAD

**Issue by meivantodorov** [aeternity/elixir-node#461]
Related to #460 while we are getting account balance we never match [:none](https://github.com/aeternity/elixir-node/blob/master/apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex#L13) case

**Comment by thepiwo** [comment]
could you think of a better name for the issue and add a linenumber or stacktrace here?

**Comment by meivantodorov** [comment]
@thepiwo  The link that I provided leads to the case. If You have better name in mind - feel free to change it.

**Comment by thepiwo** [comment]
I ask for a better name, as I don't understand it by reading, so I can't provide a better one
