### ISSUE TITLE
No function clause matching while getting more than 100 blocks

### ISSUE THREAD

**Issue by meivantodorov** [aeternity/elixir-node#465]
Looks like [here](https://github.com/aeternity/elixir-node/blob/master/apps/aecore/lib/aecore/persistence/worker.ex#L289) we are receiving `%{block: %Block{}}` when we expect `%Block{}`

**Comment by cytadela8** [comment]
What's going on with this?

**Comment by gspasov** [comment]
Resolved with PR #506
