### ISSUE TITLE
Change the Supervisor -> GenServer design pattern

### ISSUE THREAD

**Issue by gspasov** [aeternity/elixir-node#505]
As you can read [here](https://hexdocs.pm/elixir/Supervisor.Spec.html) the worker(GenServer..) type of design is now deprecated and it should be changed with [child-specs](https://hexdocs.pm/elixir/Supervisor.html#module-child-specification). This design pattern should be adopted for the whole code-base of the project.

**Comment by thepiwo** [comment]
I did read some documentation and the way we do it should be fine, I did only find one occurrence and fixed this, using the old pattern.

@cytadela8 @gspasov we should probably discuss splitting workers in handlers and api
