### ISSUE TITLE
Equalize the Genesis block structure with Epoch

### ISSUE THREAD

**Issue by gspasov** [aeternity/elixir-node#510]
We have a few differences with the Epoch Genesis block;

- [x] 1. They build the genesis block on runtime;

- [x] 2. They have predefined accounts with predefined tokens in a separate json file (possibly the initial recipients of tokens (the investors));

- [x] 3. The don't validate the genesis block as the other mined blocks (they don't have pow for the genesis block, they have it as an empty list);

- [x] 4. Nonce should be 0 respectively;

- [x] 5. The time property is to be set at 0;

- [x] 6. Miner pubkey should be with size 32bytes;

- [x] 7. Version should be 15;

- [x] 8. The root_hash should be `<<232, 183, 193, 178, 72, 97, 49, 126, 122, 247, 245, 45, 43, 120, 61, 35, 210,
   166, 103, 167, 99, 167, 85, 205, 205, 254, 50, 201, 221, 174, 64, 108>>` or in base64 format `6LfBskhhMX569/UtK3g9I9KmZ6djp1XNzf4yyd2uQGw=`

More could be added.

**Comment by HristianHristov** [comment]
Blocked by #509

**Comment by thepiwo** [comment]
@HristianHristov this should now be unblocked as #509 is resolved
