### ISSUE TITLE
RLP decode error in Block

### ISSUE THREAD

**Issue by 0legIv** [aeternity/elixir-node#536]
When there is any type of transaction in the block, running Block.rlp_decode occurs error. To reproduce this error:
```
{:ok, tx} = Account.spend(pubkey, 20, 10, <<"payload">>)
Pool.add_transaction(tx)
Miner.mine_sync_block_to_chain
rlp = Block.rlp_encode top_block
Block.rlp_decode rlp
```
`** (CaseClauseError) no case clause matching: {:ok, %Aecore.Tx.SignedTx{data: %Aecore.Tx.DataTx{fee: 10, nonce: 1, payload: %Aecore.Account.Tx.SpendTx{amount: 20, payload: "payload", receiver: %Aecore.Chain.Identifier{type: :account, value: <<136, 24, 22, 126, 201, 5, 198, 45, 83, 55, 205, 71, 249, 16, 102, 29, 188, 107, 57, 219, 49, 69, 162, 237, 221, 138, 217, 221, 34, 73, 202, 170>>}, version: 1}, senders: [%Aecore.Chain.Identifier{type: :account, value: <<136, 24, 22, 126, 201, 5, 198, 45, 83, 55, 205, 71, 249, 16, 102, 29, 188, 107, 57, 219, 49, 69, 162, 237, 221, 138, 217, 221, 34, 73, 202, 170>>}], ttl: 0, type: Aecore.Account.Tx.SpendTx}, signatures: [<<247, 20, 98, 76, 201, 239, 90, 78, 247, 118, 127, 35, 5, 171, 117, 100, 249, 220, 2, 196, 54, 195, 129, 157, 116, 51, 125, 159, 6, 253, 34, 250, 13, 154, 210, 124, 53, 160, 87, 15, 96, 225, 194, 251, 203, ...>>]}}
    (aecore) lib/aecore/chain/block.ex:111: Aecore.Chain.Block.txs_list_valid/1
    (aecore) lib/aecore/chain/block.ex:86: Aecore.Chain.Block.decode_from_list/2`

**Comment by cytadela8** [comment]
Should be a simple fix. I will look at that shortly.

**Comment by 0legIv** [comment]
There is one more error - now with the oracle extend tx.
To reproduce it:
```
Oracle.register("foo: bar", "foo: bar", 5, 5, %{ttl: 10, type: :relative})
Miner.mine_sync_block_to_chain
Oracle.extend(3, 10)
Miner.mine_sync_block_to_chain
rlp = Block.rlp_encode(Chain.top_block)
Block.rlp_decode rlp
```
Error:
```
** (ArgumentError) argument error
    (stdlib) :binary.encode_unsigned(<<3>>)
    (aecore) lib/aecore/oracle/tx/oracle_extend_tx.ex:143: Aecore.Oracle.Tx.OracleExtendTx.decode_from_list/2
    (aecore) lib/aecore/tx/data_tx.ex:390: Aecore.Tx.DataTx.rlp_decode/1
    (aecore) lib/aecore/tx/signed_tx.ex:261: Aecore.Tx.SignedTx.decode_from_list/2
    (aecore) lib/aecore/chain/block.ex:106: Aecore.Chain.Block.decode_txs_list/2
    (aecore) lib/aecore/chain/block.ex:81: Aecore.Chain.Block.decode_from_list/2
```
