### ISSUE TITLE
Channel transactions serialization adjustments

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#543]
Adjustment of channel transactions serialization. 
This excludes ChannelStateOffChain serialization required by `ChannelSlashTx` and `ChannelSoloCloseTx`.

**Comment by thepiwo** [comment]
@cytadela8 this is resolved by #623 right?

**Comment by thepiwo** [comment]
ah it is not, it will be resolved with #586

**Comment by cytadela8** [comment]
This was resolved by #669
