### ISSUE TITLE
Serialization compatibility (tests and fixes)

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#544]
To prepare for syncing with epoch we should write tests in which we bring some RLP encoded binaries from epoch and try to recreate them in our code. This issue includes also fixing problems found by the tests.

As there are many different structures and most most probably our code isn't perfect this issue should be split into smaller ones. Probably we shouldn't use `aecore_serializations_test.exs` for new tests to avoid unnecessary merge conflicts. I think we should try to make this tests thorough (check different scenarios), this should reduce any problems when we finally try to sync with epoch. 

For example:
1. Create an keypair (to be hardcoded in test)
2. Use the keypair to create a transaction in epoch. Serialize the transaction to RLP encoding in epoch. (All of this we run while developing the test and code used to create the RLP encoding can be attached as comment. The RLP encoding is to be hardcoded.)
3. Use the keypair to create identival transaction in elixr-node. Serialize the transaction to RLP encoding. (This code should be run every time the test is run)
4. In the test code compare the results from step 3 and 4. (To have more meaningful errors we can try deserializing both and comparing deserialized structures, but the binaries should also be checked.)

_If you have any questions please don't hesitate to ask me. I will probably have some example tests ready in next week. My motivation for this issue is that each one of the tests created will be quite short and simple, but together they will probably check compatibility quite well._

**Comment by thepiwo** [comment]
@cytadela8 I'll close this for now, we can reintroduce a task for this in the future if we want to test mainnet compatibility
