### ISSUE TITLE
Write step-by-step guide on how to check consensus to be epoch 0.16 compatible

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#545]
add a docs/epoch-compatibility.md with `## epoch 0.16` headline and description

**Comment by gspasov** [comment]
# Step by step buide on how to check consensus to be epoch 0.16 compatible:

## Checking Peering between 2 nodes, Sync and Gossiping Blocks/Txs

- Check that all elements of the genesis block are equal;
- Check that we can connect as peers;
- Check that we can gossip transactions between eachother;
- Check that we can gossip blocks between eachother;
- Check that if one of the nodes is on longer chain, when connected with eachother, the node with short chain will get the longer remote chain (This is done through sync);
- Check that if on same height, the more difficult chain will be accepted by the other node (when on a fork, and with same top_block_height, the nodes decide on if their chain is supperior by checking the difficulty);

## Checks for serialization for different types of Transactions:

### Spend tx: 
- Create a SpendTx, with specific amount of tokens to send, specific amount of fee, to a specific pubkey;
- Add the transaction to the pool
- Mine the next block
- Get the value of `txs_hash` key inside the `Header`
- Do the same in Epoch
- Get the `txs_hash` from the block in epoch

**If the `txs_hash` in elixir == `txs_hash` in epoch, the SpendTx is valid between the two nodes**

### Naming txs:

TBA..


### Oracle txs:

TBA..


### Channel txs:

TBA..

@d-velev, @nedelcho-delchev-tues, @Artur64, @cheezus1, @DanielaIvanova 
Please everyone related to one of the topics here, fill free to edit my comment and fill the TBA spaces, with information on how to check if we are compatible on this subject with epoch.
If you think that more should be added, fill free to add new checks as well. If you find mistakes, fill free to fix them too.
