### ISSUE TITLE
Removing the use of :sext library from the cache_key_encode/decode

### ISSUE THREAD

**Issue by 0legIv** [aeternity/elixir-node#564]
Is it possible not to use the :sext library and change it with for example: :erlang.term_to_binary, in order to remove 2 dependencies :edown and :sext, as it is used only in 2 functions.

**Comment by rdimitrovbg** [comment]
We are using ```sext``` library to serialize keys, to put inside the oracle cache tree, which does not affect main oracle Patricia Merkle Trie root hash, and we could have changed it, but I would not recommend switching to other type serialization.
Probably they (`epoch`) have their own reasons to use this type of serializations and not ```term_to_binary | binary_to_term```, as @Artur64 mentioned in his comment, about `sortable serialization`.

**Comment by thepiwo** [comment]
I propose we think of our own solution to caching instead of coping the epoch approach

**Comment by cytadela8** [comment]
After checking the code I see that epoch uses sext probably so they can query efficiently the cache tree for "all oracles and queries expiring on given block". We don't take advantage of that and this can be implemented in other ways.
