### ISSUE TITLE
Problem in oracle PMT root_hash in the chain_state

### ISSUE THREAD

**Issue by DanielaIvanova** [aeternity/elixir-node#565]
**Steps to reproduce the problem:**
Be sure that the keys are the same in both nodes.
1. Register an oracle in elixir node.
2. Register an oracle with the same data in epoch node.
**Note:** The oracle_tree root_hashes should be same in both nodes.
3. Register a query in elixir node.
4. Register a query in epoch node with the same data.
**Note:** The oracle_tree root_hashes should be same in both nodes.
After that register response in both nodes with the same data and you can see that the root_hashes are still the same in both trees.
The problem is coming when we extend the oracle.
5. Make a transaction to `extend` the oracles in both nodes with same `ttl` and `fee`
At this moment the oracle_tree root_hashes are **different**.
The most interesting thing is that when we inspect the trees all keys and values are equal.

**Useful information**
In epoch we can inspect the tree:
```
aeu_mtrees:to_list(Tree).
```
In elixir we can inspect the tree:
```
Chain.chain_state.oracles.oracle_tree |> PatriciaMerkleTree.print_trie([output: :as_pair, deserialize: false]) 
```

**Comment by cytadela8** [comment]
Could you provide some example code? I have trouble recreating Oracle transactions in epoch.

**Comment by DanielaIvanova** [comment]
@cytadela8 
https://github.com/aeternity/elixir-node/issues/545
You can follow the steps `Check transactions with Sync nodes:`

**Comment by DanielaIvanova** [comment]
I was using `wscat` for transactions in epoch.
https://github.com/aeternity/protocol/blob/epoch-v0.16.0/epoch/api/oracle_api_usage.md

**Comment by cytadela8** [comment]
I was able to reproduce! I'm searching for reason now!

**Comment by cytadela8** [comment]
I confirm a bug in MerklePatriciaTree. I will make an issue in that repo.

**Comment by cytadela8** [comment]
Actually it seems to be (at least partially) a known issue. I opened [this issue](https://github.com/aeternity/elixir-merkle-patricia-tree/issues/10) some time ago.

**Comment by cytadela8** [comment]
new issue - https://github.com/aeternity/elixir-merkle-patricia-tree/issues/13

**Comment by cytadela8** [comment]
#610 workaround resolves this issue
