### ISSUE TITLE
SignedTx is not compatible with epoch

### ISSUE THREAD

**Issue by grzegorz225** [aeternity/elixir-node#568]
A signed Transaction in the serialized form must have sorted signatures.
https://github.com/aeternity/epoch/blob/v0.16.0/apps/aetx/src/aetx_sign.erl#L133

Our signature verification currently assumes that the signatures have a 1-1 correspondence to the senders pubkey's. This will be resolved together with #533.

**Comment by gspasov** [comment]
Isn't this issue resolved with PR #572 ? If so it should be closed.

**Comment by thepiwo** [comment]
@grzegorz225 ?
