### ISSUE TITLE
Adjust the limit for transactions in a block

### ISSUE THREAD

**Issue by d-velev** [aeternity/elixir-node#591]
edit: as @gspasov said below, the limit should be changed from 100 to 10946

**Comment by d-velev** [comment]
@gspasov we won't accept an epoch block with transactions that are above our limit

**Comment by gspasov** [comment]
Wasn't there some limit to how much txs could be mined with a block? I think it was more so a limit of bytes? Do you know how does epoch limit this?

**Comment by d-velev** [comment]
@gspasov ah alright I've missed that, our limit is 100 so a change is needed anyway

**Comment by gspasov** [comment]
Will fix this
