### ISSUE TITLE
Fix test timeout in channels test

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#597]
aecore_channels_test.exs:114

**Comment by cytadela8** [comment]
Can you provide more info? What's the problem? I think I extended the test timeout at some point, because I run into timeout.

**Comment by thepiwo** [comment]
@cytadela8 I did just see this in various travis logs and local test runs, have no more information at hand right now

**Comment by cytadela8** [comment]
So it's exceeding timeout? I don't see anything else we can do for this test specifically then simply making it bigger.

In general we could create an mock proof of work for tests. Invoking cuckoo takes a lot of time.

**Comment by thepiwo** [comment]
It didn't happen the last runs any more, will close for now
