### ISSUE TITLE
Mock mining for tests

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#604]
Our tests run currently very slowly. Nearly all time is spend calculating cuckoo. This is not needed. We should create a mock mining for tests. To do that I suggest following:

1. [x] Create a behaviour that describes Aecore.Pow.Cuckoo interface. 
2. [x] Create `Aecore.Pow.Sha` module that exposes the same functionality as `Aecore.Pow.Cuckoo` and implements the behaviour, but uses Sha256 for proof of work.
2. [x] Make it configurable in config which miner is used for mining and verification in our node.
3. [x] Set `Sha` as miner for tests and make sure the difficulty doesn't increase due to automatic difficulty adjustments.
4. [x] Make sure Cuckoo test still uses Cuckoo miner. (Suggestion: probably you can leverage the possibility of setting environment variables in runtime.)

I think each of this points can be made into separate PR.

**Comment by d-velev** [comment]
Can we maybe set the expected mine rate constant to be a lot lower for tests instead?

**Comment by cytadela8** [comment]
I tried looking through all of our parameters at one point and didn't find anything to lower. If you know about something try lowering it and seeing if tests speed improves significantly.

**Comment by d-velev** [comment]
wasn't there an expected mining time constant somewhere?
