### ISSUE TITLE
Remove top block references from transactions

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#626]
`Aecore.Chain.Worker` module is for storing current state of chain and information about consensus (top block, longest chain, current chainstate), but `Aecore.Chain.Worker.top_block()` is used as a default value for `block_height` parameter in `Aecore.Tx.DataTx.validate`.

In general when block is validated we should only use previous block and previous chainstate to do that. In transactions and block validation logic there should be no references to current top block or anything like that.

**Comment by thepiwo** [comment]
@cytadela8 do I see correctly that we shouldn't have the `block_height` at all in `validate`, but in `preprocess_check` as it includes check against the chainstate, surely passimg `block_height`, without default value

**Comment by cytadela8** [comment]
Yes, we should move the check to `preprocess_checks`
