### ISSUE TITLE
DataTx does not enforce Identifier types

### ISSUE THREAD

**Issue by grzegorz225** [aeternity/elixir-node#645]
In &DataTx.init_binary/6 the types of identifiers are not checked. This could lead to proper deserialization of transactions having senders of invalid types(for instance a SpendTx with an oracle as the sender).

**Comment by cytadela8** [comment]
Something can't be a bug and enchantment at the same time :laughing: Fixing labels.

**Comment by thepiwo** [comment]
Can you check compatibility for transactions without identifier?

In general we should enforce Identifiers, but if epoch is able to create and process transactions without identifier we have to be compatible to this. @d-velev could you check this and let us know here?
