### ISSUE TITLE
Travis fails on master

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#647]
See: https://travis-ci.org/aeternity/elixir-node/builds/435770932

This is a Travis related issue an archive we download seems to have stopped existing in last hour

**Comment by cytadela8** [comment]
It seems Travis broke something, because Elixir installation doesn't work even for 1.6.6. (current 1.6) I think Travis has to fix itself.

**Comment by cytadela8** [comment]
Open issue with Travis https://github.com/travis-ci/travis-ci/issues/10170

**Comment by thepiwo** [comment]
Yeah, the problem persists with the things I just tried

**Comment by grzegorz225** [comment]
Closed via PR https://github.com/aeternity/elixir-node/pull/664
