### ISSUE TITLE
Aehttpclient test is unstable

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#666]
Sometimes Aehttpclient test fails, becouse of different transaction ordering in Pool (I think it depends on hash and that depends on generated addresses).

Example fail: 
https://travis-ci.org/aeternity/elixir-node/builds/439842704

**Comment by thepiwo** [comment]
great use for 666 as issue number :joy:

**Comment by cytadela8** [comment]
:rofl: :rofl: :rofl:
