### ISSUE TITLE
Channel Identifiers concept

### ISSUE THREAD

**Issue by DanielaIvanova** [aeternity/elixir-node#686]
@Artur64  and I familiarized deeper with channel structures and channel serializations. We found out that when epoch creates channel on_chain txs they create identifiers at the same time. Here is an example of initializing of [channel_close_solo_tx](https://github.com/aeternity/epoch/blob/v0.16.0/apps/aechannel/src/aesc_close_solo_tx.erl#L63).
In our node we create and encode identifiers right when we serialize it. Here is another [example](https://github.com/aeternity/elixir-node/blob/master/apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex#L205). 
This approach prevents us from adding channel identity checks for issue #685.
@thepiwo @cytadela8 @grzegorz225  
What do you think?

**Comment by cytadela8** [comment]
So my idea is that when the identifier type can be deduced from the field it's in (like, "initiator" - always account or "channel_id" - always channel) there is no need to use %Identifier structure in our code there. It adds unnecessary complexity. We can still be fully compatible and do all required checks by using identifiers only in serialization. Currently there are no places other then serialization in our code where the identifier type can't be deduced. In future probably such place will be receiver of a spend transaction if you would be able to target a contract with it.

**Comment by cytadela8** [comment]
In general I think we should do things the way we see it's easiest / best and not follow Epoch blindly. I didin't see a need to use Identifiers structure so I didn't do that. I just added what's needed for compatibility.

**Comment by thepiwo** [comment]
Thank you @cytadela8, I assume we did all necessary discussion on this in our call and with these comments here, so I will close this for now.
