### ISSUE TITLE
Adjust miner reward chainstate calculation

### ISSUE THREAD

**Issue by d-velev** [aeternity/elixir-node#736]
The reward for the current leader is the following: coinbase + 0.6 * sum of fees in the micro blocks in previous generation + 0.4 * sum of fees in current generation

**Comment by thepiwo** [comment]
Can you add information on how to adjust

**Comment by cytadela8** [comment]
I think this issue might be more deffictult then it seems. New rewards calculation requires access to previous block. Also if I remember correctly bitcoin-ng requires locking of rewards.

I belive this issue intersects with "Adjust block validation..."

**Comment by d-velev** [comment]
@cytadela8 I think it will just require some adjustments to calculating reward in chainstate, validation checks if the chainstate is calculated correctly so it shouldn't be touched right? I guess we will need to keep track of when to apply rewards as well

**Comment by d-velev** [comment]
blocked by #742 (requires getting previous generation from chain)

**Comment by thepiwo** [comment]
closed by https://github.com/aeternity/elixir-node/pull/798
