### ISSUE TITLE
Adjust Oracle Response Transaction serializations

### ISSUE THREAD

**Issue by Artur64** [aeternity/elixir-node#769]
Newest version of Epoch's node implements 2 new fields: `response_ttl_type`, `response_ttl_value`  in Oracle Response TX, this issue is blocked until these fields are implemented. Here is [a link](https://github.com/aeternity/protocol/blob/master/serializations.md#oracle-response-transaction) This issue is a part of #732 . Blocked by #795

**Comment by thepiwo** [comment]
Could you discuss an estimate together with the team?

**Comment by thepiwo** [comment]
Could you discuss an estimate together with the team?
