### ISSUE TITLE
Adjust Contract Call serialization

### ISSUE THREAD

**Issue by Artur64** [aeternity/elixir-node#770]
Newest version of Epoch's node implements a new field: `log` in Contract call structure, this issue is blocked until this field is implemented. Here is [a link](https://github.com/aeternity/protocol/blob/master/serializations.md#contract-call)

**Comment by thepiwo** [comment]
@cytadela8 does this overlap with some of the tasks you did create? If not, could you discuss an estimate together?

**Comment by thepiwo** [comment]
@cheezus1  does this overlap with some of the tasks you did create? If not, could you discuss an estimate together?

**Comment by thepiwo** [comment]
@cheezus1 does this overlap with some of the tasks you did create? If not, could you discuss an estimate together?

**Comment by cheezus1** [comment]
yes, it does overlap, with #753 . This issue should be resolved there.

**Comment by Artur64** [comment]
Closed this issue, reason: overlaps with #753
