### ISSUE TITLE
add release notes for 0.2.0 

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#803]
include a description of what has changed from 0.1.0

you don't have to include installation and configuration, just reference https://github.com/aeternity/elixir-node/blob/master/docs/release-notes/release-notes-0.1.0.md

"Retrieve the software for running a node"
and "Running your node" should be included

@DanielaIvanova @Artur64 could you do this and then @cytadela8 add all the changes made in channels?

**Comment by DanielaIvanova** [comment]
@cytadela8 
We are ready with our part.

**Comment by cytadela8** [comment]
Channels release notes are ready.
