### ISSUE TITLE
上坟（go to the grave）

### ISSUE THREAD

**Issue by WilliamSoCreat** [aeternity/elixir-node#813]
“清明时节雨纷纷，路上行人欲断魂。”
The elixir community is relatively centralized
for example
I posted a relatively mainstream recruitment website in China
Then retracted my message as unmoderable
I think this assumes that you are a bad person, you need to prove to the center that you are a good person, otherwise you cannot proof
This is contrary to the spirit of the blockchain, which is strongly regulated
So we should refuse to use elixir
“好雨知时节”

**Comment by thepiwo** [comment]
doesn't seem relevant here
